site:
  stitle: vcnt.eu
  baseUrl: https://example.com

backend:
  name: git-gateway
  branch: main 
  site_url: https://vcnt.eu
  logo_url: https://vcnt.eu/images/logo.png

media_folder: "src/images/posts/2023"
public_folder: "/images/posts/2023"

editor:
  preview: true

stylesheets:
  - /css/main.css
  - /css/syntax.css

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Preview Image", name: "previewImage", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Post URL", name: "postUrl", widget: "string", default: "{{ page.url | url }}" }
      - { label: "Body", name: "body", widget: "markdown" }
 
