backend:
  name: git-gateway
  branch: main 
  publish_mode: editorial_workflow
  site_url: https://vcnt.eu
  logo_url: https://vcnt.eu/images/logo.png
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"

    label: "Pages"

    folder: "src"

    create: true

    slug: "{{slug}}"

    fields: 

      - { label: "Title", name: "title", widget: "string" }

      - { label: "Layout", name: "layout", widget: "list", default: ["base"] }

      - { label: "Body", name: "body", widget: "markdown" }
