site:
  stitle: vcnt.eu
  baseUrl: https://vcnt.eu

backend:
  name: git-gateway
  branch: main 
  site_url: https://vcnt.eu
  logo_url: https://vcnt.eu/images/logo.png

media_folder: "src/images/posts"
public_folder: "/images/posts"

editor:
  preview: true

stylesheets:
  - /css/main.css
  - /css/syntax.css

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
     - { label: "Preview Image", name: "previewImage", widget: "image", value_type: "string", default: "", media_library: { config: { fileMeta: [{ media_folder: "src/images/posts", public_folder: "/images/posts" }], allow_multiple: false }, enabled: true }, hint: "Enter the path to the preview image. Make sure to remove 'src/' from the path.", required: false, value_template: '{{ value | transformMediaPath }}' }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Post URL", name: "postUrl", widget: "string", default: "{{ page.url | url }}" }
      - { label: "Body", name: "body", widget: "markdown" }
 
